language: cpp
compiler:
  - gcc
  - clang
before_script:
  - sudo apt-get install -y cmake
  - wget https://github.com/google/googletest/archive/release-1.8.0.zip
  - unzip -q release-1.8.0.zip
  - cd googletest-release-1.8.0
  - cmake .
  - make
  - cd ..
script:
  - cd examples
  - scons
  - cd ../test
  - scons check
